//import LangText from "./lang/LangText"

export const LANG_TEXT_KEY = "langKey"

export const NEWS_WIDGETS_NEW_CONST = {
    PORTFOLIO_NEWS: "PORTFOLIO NEWS",
    ALL_NEWS: "ALL NEWS",
    RESULTS: "RESULTS",
    GLOBAL_NEWS: "GLOBAL NEWS",
    FIXED_INCOME: "FIXED INCOME",
    BLOCK_DEALS: "Block_Details",
    COMMODITIES: "COMMODITIES",
    COMMENTARY: "COMMENTARY",
    SPECIAL_COVERAGE: "SPECIAL COVERAGE",
    BUDGET: "BUDGET",
    CORPORATE_ACTION: "CORPORATE ACTION",
    ELECTION: "ELECTION"
}

export const NEWS_MENUS_ARRAY_NEW_CONST = [
    { name: NEWS_WIDGETS_NEW_CONST.PORTFOLIO_NEWS, langKey: "PORTFOLIO_NEWS" },
    { name: NEWS_WIDGETS_NEW_CONST.BLOCK_DEALS, langKey: "BLOCK_DEALS" },
    { name: NEWS_WIDGETS_NEW_CONST.ALL_NEWS, langKey: "ALL_NEWS" },
    { name: NEWS_WIDGETS_NEW_CONST.RESULTS, langKey: "RESULTS" },
    { name: NEWS_WIDGETS_NEW_CONST.ELECTION, langKey: "ELECTION" },
    { name: NEWS_WIDGETS_NEW_CONST.GLOBAL_NEWS, langKey: "GLOBAL_NEWS" },
    { name: NEWS_WIDGETS_NEW_CONST.FIXED_INCOME, langKey: "FIXED_INCOME" },
    { name: NEWS_WIDGETS_NEW_CONST.COMMODITIES, langKey: "COMMODITIES" },
    { name: NEWS_WIDGETS_NEW_CONST.COMMENTARY, langKey: "COMMENTARY" },
    { name: NEWS_WIDGETS_NEW_CONST.SPECIAL_COVERAGE, langKey: "SPECIAL_COVERAGE" },
    { name: NEWS_WIDGETS_NEW_CONST.BUDGET, langKey: "BUDGET" },
    { name: NEWS_WIDGETS_NEW_CONST.CORPORATE_ACTION, langKey: "CORPORATE_ACTION" }

]

export const NEWS_FILTER_NEW_CONST = [
    { [LANG_TEXT_KEY]: "RECENT", name: "RECENT", iconEnable: false },
    { [LANG_TEXT_KEY]: "LAST_HOUR", name: "LAST HOUR", iconEnable: false },
    { [LANG_TEXT_KEY]: "LAST_24_HOURS", name: "LAST 24 HOURS", iconEnable: false },
    { [LANG_TEXT_KEY]: "LAST_WEEK", name: "LAST WEEK", iconEnable: false },
    { [LANG_TEXT_KEY]: "LAST_MONTH", name: "LAST MONTH", iconEnable: false },
    { [LANG_TEXT_KEY]: "CUSTOM_DATE", name: "CUSTOM DATE", iconEnable: true }
]

export const NEWS_FILTER_CORPORATE_ACTION_NEW_CONST = [
    { [LANG_TEXT_KEY]: "TODAY", name: "TODAY", iconEnable: false },
    { [LANG_TEXT_KEY]: "NEXT_WEEK", name: "NEXT WEEK", iconEnable: false },
    { [LANG_TEXT_KEY]: "NEXT_2_WEEKS", name: "NEXT 2 WEEKS", iconEnable: false },
    { [LANG_TEXT_KEY]: "NEXT_1_MONTH", name: "NEXT 1 MONTH", iconEnable: false },
]

export const NEWS_FILTER_MENU_NEW_CONST = {
    RECENT: "RECENT",
    LAST_HOUR: "LAST HOUR",
    LAST_24_HOURS: "LAST 24 HOURS",
    LAST_WEEK: "LAST WEEK",
    LAST_MONTH: "LAST MONTH",
    CUSTOM_DATE: "CUSTOM DATE",
    TODAY: "TODAY",
    NEXT_WEEK: "NEXT WEEK",
    NEXT_2_WEEKS: "NEXT 2 WEEKS",
    NEXT_1_MONTH: "NEXT 1 MONTH"
}

export const NCD_MENUS_NEW_CONST = {
    LIST_NCD: "List of NCDs",
    ORDERBOOK: "Order Book",
}

export const NCD_MENU_ARRAY_NEW_CONST = [
    { name: NCD_MENUS_NEW_CONST.LIST_NCD, langKey: "LIST_NCD" },
    { name: NCD_MENUS_NEW_CONST.ORDERBOOK, langKey: "ORDERBOOK" },
]

export const NCD_DIALOGS_NEW_CONST = {
    APPLY_ORDER: "APPLY_ORDER",
    SHOW_SERIES_LIST: "SHOW_SERIES_LIST",
    GOTO_PLACE_ORDER_SCREEN: "GOTO_PLACE_ORDER_SCREEN",
    GOTO_CONFIRM_ORDER: "GOTO_CONFIRM_ORDER",
    ORDER_CONFIRMATION: "ORDER_CONFIRMATION",
    ORDER_RESULT: "ORDER_RESULT",
    CANCEL_ORDER: "CANCEL_ORDER",
    CANCEL_ORDER_RESULT: "CANCEL_ORDER_RESULT",
}

export const NCD_SERIES_LIST_NEW_CONST = {
    SERIES_1: "SERIES 1",
    SERIES_2: "SERIES 2",
    SERIES_3: "SERIES 3",
    SERIES_4: "SERIES 4",
    SERIES_5: "SERIES 5",
    SERIES_6: "SERIES 6",
    SERIES_7: "SERIES 7",
    SERIES_8: "SERIES 8",
    SERIES_9: "SERIES 9",
    SERIES_10: "SERIES 10"
}

export const NCD_MESSAGES_NEW_CONST = {
    QUANTITY_RANGE_ERROR: "Quantity out of range",
    QUANTITY_MULTIPLE_ERROR: "Quantity value should be a multiple of multiple of quantity"
}

export const NCD_ORDER_STATUS_NEW_CONST = {
    REJECTED: "Rejected",
    PENDING: "Pending",
    // OPEN: "open",
    CANCELLED: "Cancel",
    SUCCESS: "Success"
}

export const BO_REPORTS_MENUS_NEW_CONST = {
    FINANCIAL_LEDGER: "FINANCIAL LEDGER",
    PNL_REPORT: "P&L REPORT",
    TAX_REPORT: "TAX REPORT",
    INTEREST_REPORT: "INTEREST REPORT",
    TRADE_SUMMARY: "TRADE SUMMARY",
    FUND_TRANSACTION: "FUND TRANSACTION",
    COST_REPORT: "COST REPORT",
    CONTRACT_NOTE_DOWNLOAD: "CONTRACT NOTE DOWNLOAD",
    VIEW_LAST_TRANSACTION: "VIEW LAST 10 TRANSACTIONS",
    CLIENT_HOLDINGS: "CLIENT HOLDINGS",
    DIVIDEND_REPORT: "DIVIDEND REPORT",
    DP_TRANSACTION: "DP TRANSACTION",
    BROKERAGE_REPORT: "BROKERAGE REPORT",
    LTCG_REPORT: "LTCG REPORT",
    DP_BILL_CHARGES: "DP BILL CHARGES"
}

export const BO_REPORTS_MENUS_ARRAY_NEW_CONST = [
    { name: BO_REPORTS_MENUS_NEW_CONST.FINANCIAL_LEDGER, langKey: "FINANCIAL_LEDGER" },
    { name: BO_REPORTS_MENUS_NEW_CONST.CLIENT_HOLDINGS, langKey: "CLIENT_HOLDINGS" },
    { name: BO_REPORTS_MENUS_NEW_CONST.PNL_REPORT, langKey: "PNL_REPORT" },
    { name: BO_REPORTS_MENUS_NEW_CONST.TAX_REPORT, langKey: "TAX_REPORT" },
    { name: BO_REPORTS_MENUS_NEW_CONST.INTEREST_REPORT, langKey: "INTEREST_REPORT" },
    { name: BO_REPORTS_MENUS_NEW_CONST.TRADE_SUMMARY, langKey: "TRADE_SUMMARY" },
    { name: BO_REPORTS_MENUS_NEW_CONST.FUND_TRANSACTION, langKey: "FUND_TRANSACTION" },
    { name: BO_REPORTS_MENUS_NEW_CONST.COST_REPORT, langKey: "COST_REPORT" },
    { name: BO_REPORTS_MENUS_NEW_CONST.VIEW_LAST_TRANSACTION, langKey: "VIEW_LAST_TRANSACTION" },
    { name: BO_REPORTS_MENUS_NEW_CONST.DIVIDEND_REPORT, langKey: "DIVIDEND_REPORT" },
    { name: BO_REPORTS_MENUS_NEW_CONST.DP_TRANSACTION, langKey: "DP_TRANSACTION" },
    { name: BO_REPORTS_MENUS_NEW_CONST.LTCG_REPORT, langKey: "LTCG_REPORT" },
    { name: BO_REPORTS_MENUS_NEW_CONST.CONTRACT_NOTE_DOWNLOAD, langKey: "CONTRACT_NOTE_DOWNLOAD" },
    { name: BO_REPORTS_MENUS_NEW_CONST.BROKERAGE_REPORT, langKey: "BROKERAGE_REPORT" },
    { name: BO_REPORTS_MENUS_NEW_CONST.DP_BILL_CHARGES, langKey: "DP_BILL_CHARGES" }

]

export const SYMBOL_RESULT_HEADER_NEW_CONST = {
    ALL: "All",
    CASH: "Cash",
    FUTURE: "Future",
    OPTIONS: "Options",
}

export const SYMBOL_RESULT_HEADER_ARRAY_NEW_CONST = [
    { name: SYMBOL_RESULT_HEADER_NEW_CONST.ALL, langKey: "ALL" },
    { name: SYMBOL_RESULT_HEADER_NEW_CONST.CASH, langKey: "CASH" },
    { name: SYMBOL_RESULT_HEADER_NEW_CONST.FUTURE, langKey: "FUTURE" },
    { name: SYMBOL_RESULT_HEADER_NEW_CONST.OPTIONS, langKey: "OPTIONS" },

]

export const BO_REPORTS_FILTER_NEW_CONST = [
    { [LANG_TEXT_KEY]: "THIS_MONTH", name: "THIS MONTH", iconEnable: false },
    { [LANG_TEXT_KEY]: "LAST_MONTH", name: "LAST MONTH", iconEnable: false },
    { [LANG_TEXT_KEY]: "CURRENT_FY", name: "CURRENT FY", iconEnable: false },
    { [LANG_TEXT_KEY]: "LAST_FY", name: "LAST FY", iconEnable: false },
    { [LANG_TEXT_KEY]: "CUSTOM_DATE", name: "CUSTOM DATE", iconEnable: true },

]

export const BO_REPORTS_TAX_FILTER_NEW_CONST = [
    { [LANG_TEXT_KEY]: "FY_2022_23", name: "FY2022-23" },
    { [LANG_TEXT_KEY]: "FY_2021_22", name: "FY2021-22" },
    { [LANG_TEXT_KEY]: "FY_2020_21", name: "FY2020-21" },
    { [LANG_TEXT_KEY]: "FY_2019_20", name: "FY2019-20" },
]

export const BO_REPORTS_PNL_FILTER_NEW_CONST = [
    { [LANG_TEXT_KEY]: "THIS_MONTH", name: "THIS MONTH", iconEnable: false },
    { [LANG_TEXT_KEY]: "LAST_MONTH", name: "LAST MONTH", iconEnable: false },
    { [LANG_TEXT_KEY]: "CURRENT_FY", name: "CURRENT FY", iconEnable: false },
    { [LANG_TEXT_KEY]: "LAST_FY", name: "LAST FY", iconEnable: false },
    { [LANG_TEXT_KEY]: "CUSTOM_DATE", name: "CUSTOM DATE", iconEnable: true },

]

export const BO_REPORTS_PNL_HOLDINGS_FILTER_NEW_CONST = [
    { [LANG_TEXT_KEY]: "ALL_HOLDINGS", name: "ALL HOLDINGS", key: "ALL" },
    { [LANG_TEXT_KEY]: "POSITIVE_HOLDINGS", name: "POSITIVE HOLDINGS", key: "POSITIVE" },
    { [LANG_TEXT_KEY]: "ZERO_HOLDINGS", name: "ZERO HOLDINGS", key: "ZERO" },

]

// export const BO_REPORTS_FILTER_MENU = {
//     THIS_MONTH: "THIS MONTH",
//     LAST_MONTH: "LAST MONTH",
//     LAST_YEAR: "LAST YEAR",
//     CUSTOM_DATE: "CUSTOM DATE",

// }

export const BO_REPORTS_FILTER_MENU_NEW_CONST = {
    THIS_MONTH: "THIS MONTH",
    LAST_MONTH: "LAST MONTH",
    CURRENT_FY: "CURRENT FY",
    LAST_FY: "LAST FY",
    CUSTOM_DATE: "CUSTOM DATE",

}

export const BO_REPORTS_TAX_FILTER_MENU_NEW_CONST = {
    FY_2022_23: "FY2022-23",
    FY_2021_22: "FY2021-22",
    FY_2020_21: "FY2020-21",
    FY_2019_20: "FY2019-20",
}

export const BO_REPORTS_PNL_FILTER_MENU_NEW_CONST = {
    THIS_MONTH: "THIS MONTH",
    LAST_MONTH: "LAST MONTH",
    CURRENT_FY: "CURRENT FY",
    LAST_FY: "LAST FY",
    CUSTOM_DATE: "CUSTOM DATE",
}

export const BO_REPORTS_PNL_HOLDINGS_FILTER_MENU_NEW_CONST = {
    ALL_HOLDINGS: "ALL HOLDINGS",
    POSITIVE_HOLDINGS: "POSITIVE HOLDINGS",
    ZERO_HOLDINGS: "ZERO HOLDINGS"
}

export const BO_REPORTS_TAB_OPTIONS_NEW_CONST = {
    EQUITY: 'EQUITY',
    DERIVATIVE: 'DERIVATIVE'
}

export const BO_REPORT_TYPES_NEW_CONST = [
    { [LANG_TEXT_KEY]: "EQUITY", name: BO_REPORTS_TAB_OPTIONS_NEW_CONST.EQUITY },
    { [LANG_TEXT_KEY]: "DERIVATIVE", name: BO_REPORTS_TAB_OPTIONS_NEW_CONST.DERIVATIVE }
]
export const BO_REPORTS_FINANCIAL_OPTIONS_NEW_CONST = {
    QUICK_SNAPSHOT: 'QUICK SNAPSHOT',
    DETAILED_REPORT: 'DETAILED REPORT'
}

export const BO_REPORT_FINANCIAL_TYPES_NEW_CONST = [
    { [LANG_TEXT_KEY]: "QUICK_SNAPSHOT", name: BO_REPORTS_FINANCIAL_OPTIONS_NEW_CONST.QUICK_SNAPSHOT },
    {[LANG_TEXT_KEY]: "DETAILED_REPORT", name: BO_REPORTS_FINANCIAL_OPTIONS_NEW_CONST.DETAILED_REPORT }
]

export const BO_REPORTS_FINANCIAL_FILTER_MENU_NEW_CONST = {
    ALL: "ALL",
    NSE_EQ: "NSE EQ",
    NSE_FO: "NSE FO",
    BSE_EQ: "BSE EQ",
    BSE_FO: "BSE FO",
    MFSSL: "MFSS",
    MTF: "MTF"

}

export const BO_REPORTS_FINANCIAL_FILTER_NEW_CONST = [
    { [LANG_TEXT_KEY]: "ALL", name: BO_REPORTS_FINANCIAL_FILTER_MENU_NEW_CONST.ALL, key: "all", apiKey: "ALL" },
    {
        [LANG_TEXT_KEY]: "NSE EQ", name: BO_REPORTS_FINANCIAL_FILTER_MENU_NEW_CONST.NSE_EQ,
        key: "nse_eq", apiKey: "NSE"
    },
    {
        [LANG_TEXT_KEY]: "NSE FO", name: BO_REPORTS_FINANCIAL_FILTER_MENU_NEW_CONST.NSE_FO,
        key: "nse_fo", apiKey: "NFO"
    },
    {
        [LANG_TEXT_KEY]: "BSE EQ", name: BO_REPORTS_FINANCIAL_FILTER_MENU_NEW_CONST.BSE_EQ,
        key: "bse_eq", apiKey: "BSE"
    },
    {
        [LANG_TEXT_KEY]: "BSE FO", name: BO_REPORTS_FINANCIAL_FILTER_MENU_NEW_CONST.BSE_FO,
        key: "bse_fo", apiKey: "BFO"
    },
    { [LANG_TEXT_KEY]: "MFSS", name: BO_REPORTS_FINANCIAL_FILTER_MENU_NEW_CONST.MFSSL, key: "mfss", apiKey: "MFSS" },
    { [LANG_TEXT_KEY]: "MTF", name: BO_REPORTS_FINANCIAL_FILTER_MENU_NEW_CONST.MTF, key: "mtf", apiKey: "MTF" },
]

export const BO_REPORTS_INTEREST_REPORT_OPTIONS_NEW_CONST = {
    DPC: "Delay Payment Charges (DPC)",
    MTFF: "Margin Trade Financing (MTF)"
}

export const BO_REPORTS_INTEREST_REPORT_TYPES_NEW_CONST = [
    { [LANG_TEXT_KEY]: "DPC", name: BO_REPORTS_INTEREST_REPORT_OPTIONS_NEW_CONST.DPC },
    {  [LANG_TEXT_KEY]:"MTFF", name: BO_REPORTS_INTEREST_REPORT_OPTIONS_NEW_CONST.MTFF }
]

export const BO_REPORTS_BROKERAGE_FILTER_NEW_CONST = [
    { [LANG_TEXT_KEY]: "THIS_MONTH", name: "THIS MONTH", iconEnable: false },
    { [LANG_TEXT_KEY]: "LAST_MONTH", name: "LAST MONTH", iconEnable: false },
    { [LANG_TEXT_KEY]: "CURRENT_FY", name: "CURRENT FY", iconEnable: false },
    { [LANG_TEXT_KEY]: "LAST_FY", name: "LAST FY", iconEnable: false },
    { [LANG_TEXT_KEY]: "CUSTOM_DATE", name: "CUSTOM DATE", iconEnable: true },

]

export const BO_REPORTS_BROKERAGE_FILTER_MENU_NEW_CONST = {
    THIS_MONTH: "THIS MONTH",
    LAST_MONTH: "LAST MONTH",
    CURRENT_FY: "CURRENT FY",
    LAST_FY: "LAST FY",
    CUSTOM_DATE: "CUSTOM DATE",
}

export const AF_EVENT_NAMES_NEW_CONST = {
    LOGIN: "LOGIN",
    WATCHLIST: "WATCHLIST",
    ORDERPAD: "ORDERPAD",
    MARKET: "MARKET",
    ALERT: "ALERT",
    IDEAS: "IDEAS",
    HOLDINGS: "HOLDINGS",
    NETPOSITION: "NETPOSITION",
    ORDERBOOK: "ORDERBOOK",
    NOTIFICATION: "NOTIFICATION",
    FUNDS: "FUNDS",
    IPO: "IPO",
    NCD: "NCD",
    REPORT: "REPORT",
    NEWS: "NEWS",
    MENUS: "MENUS",
    PROFILE: "PROFILE",
    HELP_SUPPORT: "HELP AND SUPPORT",
    SETTINGS: "SETTINGS",
    DASHBOARD: "DASHBOARD",
    LAS: "LAS_MENU",
    INDICES: "INDICES",
    SCANNERS: "SCANNERS",
    PLEDGE: "PLEDGE",
    EDIS: "EDIS",
    DOWNLOAD:"DOWNLOAD",
}

export const  AF_EVENT_CATEOGORY_TYPES_NEW_CONST= {
    LOGIN_SUCCESS: "LOGIN SUCCESS",
    LOGIN_FAILURE: "LOGIN FAILURE",
    LOGIN_ATTEMPTS: "LOGIN NO OF ATTEMPTS",
    WATCHLIST_ATTEMPTS: "CREATE WATCHLIST",
    WATCHLIST_SUCCESS_COUNT: "WATCHLIST SUCCESS COUNT",
    WATCHLIST_FAILURE_COUNT: "WATCHLIST FAILURE COUNT",
    WATCHLIST_BUY: "WATCHLIST_BUY",
    QUOTE: "QUOTE",
    AF_CHART: "CHART",
    MORE: "MORE",
    SEARCH: "SEARCH",
    DELETE: "DELETE",
    MODIFY: "MODIFY",
    MARKET_MENU_CLICK: "MARKET MENU",
    ALERT_MENU_CLICK: "ALERT MENU",
    IDEAS_MENU_CLICK: "IDEAS MENU",
    IDEAS_VIEW_MORE: "IDEAS VIEW MORE",
    BS: "BUY/SELL",
    HOLDINGS_TAB: "HOLDINGS TAB",
    NETPOSITION_TAB: "NETPOSITION TAB",
    ORDERBOOK_TAB: "ORDERBOOK_TAB",
    NOTIFICATION_TAB: "NOTIFICATION TAB",
    FUNDS_MENU:"FUND MENU",
    FUND_VIEW: "FUND VIEW",
    ADD_FUND: "ADD FUNDS",
    CANCEL_FUND: "CANCEL FUND",
    WITHDRAW_SUCCESS: "WITHDRAW SUCCESS",
    PENDING_ALERT: "PENDING ALERT",
    TRIGERED_ALERT: "TRIGGERD ALERT",
    IPO_CLICK: "IPO CLICK",
    NCD_CLICK:"NCD CLICK",
    LIST_NCD:"LIST OF NCD",
    OPEN_IPO: "OPEN IPO",
    UPCOMING_IPO: "UPCOMING IPO",
    CLOSED_IPO: "CLOSED IPO",
    IPO_ORDERBOOK: "IPO ORDERBOOK",
    IPO_ORDER_HISTORY: "IPO ORDER HISTORY",
    BO_REPORT: "BO REPORT",
    CLIENT_HOLDINGS: "CLIENT HOLDINGS",
    DOWNLOAD: "DOWNLOAD",
    NCD_ORDER_PLACEMENT_SUCCESS: "NCD ORDER PLACEMENT SUCCESS",
    NCD_ORDER_PLACEMENT_FAILURE: "NCD ORDER PLACEMENT FAILURE",
    // DOWNLOAD_SUCCESS: "DOWNLOAD SUCCESS",
    // DOWNLOAD_FAILURE: "DOWNLOAD FAILURE",
    BROKERAGE_REPORT: "BROKERAGE REPORT",
    CONTRACT_NOTE_DOWNLOAD: "CONTRACT NOTE DOWNLOAD",
    COST_REPORT: "COST REPORT",
    DIVIDEND_REPORT: "DIVIDEND REPORT",
    DP_BILL_CHARGES: "DP BILL CHARGES",
    DP_TRANSACTION: "DP TRANSACTION",
    FINANCIAL_LEDGER: "FINANCIAL LEDGER",
    FUND_TRANSACTIONS: "FUND TRANSACTIONS",
    INTEREST_REPORT: "INTEREST REPORT",
    DAYS_TO_LONG_TERM: "DAYS TO LONGTERM ",
    PNL_REPORT: "PNL REPORT",
    TAX_REPORT: "TAX REPORT",
    TRADE_SUMMARY: "TRADE SUMMARY",
    VIEW_LAST_TRANSACTION: "VIEW LAST TRANSACTION",
    NEWS_TAB: "NEWS TAB",
    WEBSITE: "SAMADHAN WEBSITE",
    DEMO: "DEMO",
    PWD_CHANGED: "PASSWORD CHANGED",
    DASHBOARD_MENU: "DASHBOARD MENU",
    ORDERPAD_SUCCESS: "ORDER SUCCESS",
    ORDERPAD_REJECTED: "ORDER REJECTED",
    LAS_MENU: "LAS MENU",
    ELIGIBLE_USER: "ELIGIBLE_USER",
    APPLY_LOAN: "APPLY LOAN",
    UNABLE_TO_APPLY_LOAN: "UNABLE TO APPLY LOAN",
    E_AGREEMENT_MANDATE_COMPLETE: "E-AGREEMENT MANDATE COMPLETE",
    E_AGREEMENT_MANDATE_NOT_COMPLETE: "E-AGREEMENT MANDATE NOT COMPLETE",
    LAS_SERVICE_JOURNEY: "LAS SERVICE JOURNEY",
    LAS_ONBOARDING: "LAS ONBOARDING JOURNEY",
    RECHECK_SUCCESS: "LAS RECHECK SUCCESS",
    RECHECK_FAILURE: "LAS RECHECK FAILURE",
    E_PLEDGE_OTP_VERIFICATION_FAILURE: "E-PLEDGE OTP VERIFICATION FAILURE",
    E_PLEDGE_OTP_VERIFICATION_SUCCESS: "E-PLEDGE OTP VERIFICATION SUCCESS",
    E_PLEDGE_CONFIRM_FAILURE: "E-PLEDGE CONFIRM FAILURE",
    E_PLEDGE_CONFIRM: "E-PLEDGE CONFIRM",
    APPLY_IPO: "APPLY IPO",
    CANCEL_IPO: "CANCEL IPO",
    CANCEL_IPO_SUCCESS: "CANCEL IPO SUCCESS",
    CANCEL_IPO_FAILURE: "CANCEL IPO FAILURE",
    APPLY_NCD: "APPLY NCD",
    CANCEL_NCD_SUCCESS: "CANCEL NCD SUCCESS",
    CANCEL_NCD_FAILURE: "CANCEL NCD FAILURE",
    WITHDRAW_AMT_OTP_SUCCESS: "WITHDRAW AMOUNT OTP SUCCESS",
    WITHDRAW_AMT_OTP_FAILURE: "WITHDRAW AMOUNT OTP FAILURE",
    STATEMENT_SUCCESS: "LAS STATEMENT SUCCESS",
    STATEMENT_FAILURE: "LAS STATEMENT FAILURE",
    INDICES_CLICK: "INDICES CLICK",
    SCANNERS_CLICK: "SCANNERS CLICK",
    DOWNLOAD_PDF: "DOWNLOAD PDF",
    DOWNLOAD_EXCEL: "DOWNLOAD EXCEL",
    SET_ALERT: "SET ALERT",
    E_PLEDGE: "E PLEDGE",
    EDIS: "EDIS",
}

export const SYMBOL_INSTRUMENT_TYPE_NEW_CONST = {
    EQUITYSTK: "STK",
    FUTURESTK: "FUTSTK",
    OPTIONSTK: "OPTSTK",
    EQUITYIDX: "IDX",
    FUTUREIDX: "FUTIDX",
    OPTIONIDX: "OPTIDX"
}

export const MTF_DIALOGS_NEW_CONST = {
    E_PLEDGE_ALERT: "E_PLEDGE_ALERT",
    PLEDGE_CONFIRM: "PLEDGE_CONFIRM"
}

export const TRADESUMMARY_DIALOGS_NEW_CONST = {
    EDIT_CONFIRMATION: "EDIT_CONFIRMATION",
}

export const DYNAMIC_LINK_SCREEN_NEW_CONST = {
    IPO:"IPO",
    IDEAS:"IDEAS",
    FUND:"FUND",
    EDIS:"EDIS",
    PLEDGE:"PLEDGE",
    REPORTS:"REPORTS",
    ORDERPAD:"ORDERPAD",
    QUOTE:"QUOTE",
    NEWS:"NEWS",
    MARKETS:"MARKETS",
    LAS:"LAS",
    MARKETSMITH:"MARKETSMITH",
    EVOTE:"EVOTE"
}

export const SUBSCRIPTION_STATUS_NEW_CONST = {
    NEW_USER: "NEW USER",
    SUBSCRIBED_USER: "SUBSCRIBED USER",
    SUBSCRIPTION_EXPIRED: "SUBSCRIPTION EXPIRED",
    PENDING: "PENDING"
}
export const FEEDBACK_OPTIONS_NEW_CONST = [
    "Technical Issues",
    "I don’t use this service enough",
    "Cost-related reasons",
    "Other"
]

export const DDPI_STATUS_NEW_CONST = {
    NO: "NO",
    YES: "YES"
}
export const OFS_MENUS_FROM_NEW ={
    ONGOING_OFS:"ONGOING OFS",
    UPCOMING_OFS: "UPCOMING OFS",
    ORDERBOOK: "ORDERBOOK",
}
export const OFS_DIALOGS_FROM_NEW={
    APPLY_ORDER: "APPLY_ORDER",
    ORDER_CONFIRMATION: "ORDER_CONFIRMATION",
    ORDER_RESULT: "ORDER_RESULT",
    MODIFY_ORDER: "MODIFY_ORDER",
    CANCEL_ORDER: "CANCEL_ORDER",
    CANCEL_ORDER_RESULT: "CANCEL_ORDER_RESULT",
}